CREATE TABLE country
(
    ID          INTEGER PRIMARY KEY autoincrement,
    name        TEXT,
    flag        TEXT,
    continent   INTEGER,
    ratio       REAL,
    description TEXT
);
INSERT INTO country(name, flag, ratio, description) VALUES('Afghanistan', 'assets/images/flag-of-Afghanistan.png', 100, 'Afghanistan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Albania', 'assets/images/flag-of-Albania.png', 100, 'Albania is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Algeria', 'assets/images/flag-of-Algeria.png', 100, 'Algeria is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Andorra', 'assets/images/flag-of-Andorra.png', 100, 'Andorra is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Angola', 'assets/images/flag-of-Angola.png', 100, 'Angola is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Antigua', 'assets/images/flag-of-Antigua.png', 100, 'Antigua is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Argentina', 'assets/images/flag-of-Argentina.png', 100, 'Argentina is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Armenia', 'assets/images/flag-of-Armenia.png', 100, 'Armenia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Australia', 'assets/images/flag-of-Australia.png', 100, 'Australia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Austria', 'assets/images/flag-of-Austria.png', 100, 'Austria is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Azerbaijan', 'assets/images/flag-of-Azerbaijan.png', 100, 'Azerbaijan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Bahamas', 'assets/images/flag-of-Bahamas.png', 100, 'Bahamas is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Bahrain', 'assets/images/flag-of-Bahrain.png', 100, 'Bahrain is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Bangladesh', 'assets/images/flag-of-Bangladesh.png', 100, 'Bangladesh is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Barbados', 'assets/images/flag-of-Barbados.png', 100, 'Barbados is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Belarus', 'assets/images/flag-of-Belarus.png', 100, 'Belarus is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Belgium', 'assets/images/flag-of-Belgium.png', 100, 'Belgium is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Belize', 'assets/images/flag-of-Belize.png', 100, 'Belize is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Benin', 'assets/images/flag-of-Benin.png', 100, 'Benin is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Bhutan', 'assets/images/flag-of-Bhutan.png', 100, 'Bhutan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Bolivia', 'assets/images/flag-of-Bolivia.png', 100, 'Bolivia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Bosnia Herzegovina', 'assets/images/flag-of-Bosnia-Herzegovina.png', 100, 'Bosnia Herzegovina is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Botswana', 'assets/images/flag-of-Botswana.png', 100, 'Botswana is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Brazil', 'assets/images/flag-of-Brazil.png', 100, 'Brazil is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Brunei', 'assets/images/flag-of-Brunei.png', 100, 'Brunei is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Bulgaria', 'assets/images/flag-of-Bulgaria.png', 100, 'Bulgaria is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Burkina Faso', 'assets/images/flag-of-Burkina-Faso.png', 100, 'Burkina Faso is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Burundi', 'assets/images/flag-of-Burundi.png', 100, 'Burundi is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Cabo Verde', 'assets/images/flag-of-Cabo-Verde.png', 100, 'Cabo Verde is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Cambodia', 'assets/images/flag-of-Cambodia.png', 100, 'Cambodia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Cameroon', 'assets/images/flag-of-Cameroon.png', 100, 'Cameroon is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Canada', 'assets/images/flag-of-Canada.png', 100, 'Canada is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Central African Republic', 'assets/images/flag-of-Central-African-Republic.png', 100, 'Central African Republic is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Chad', 'assets/images/flag-of-Chad.png', 100, 'Chad is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Chile', 'assets/images/flag-of-Chile.png', 100, 'Chile is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('China', 'assets/images/flag-of-China.png', 100, 'China is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Colombia', 'assets/images/flag-of-Colombia.png', 100, 'Colombia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Comoros', 'assets/images/flag-of-Comoros.png', 100, 'Comoros is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Congo Democratic Republic of', 'assets/images/flag-of-Congo-Democratic-Republic-of.png', 100, 'Congo Democratic Republic of is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Congo', 'assets/images/flag-of-Congo.png', 100, 'Congo is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Costa Rica', 'assets/images/flag-of-Costa-Rica.png', 100, 'Costa Rica is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Cote d Ivoire', 'assets/images/flag-of-Cote-d-Ivoire.png', 100, 'Cote d Ivoire is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Croatia', 'assets/images/flag-of-Croatia.png', 100, 'Croatia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Cuba', 'assets/images/flag-of-Cuba.png', 100, 'Cuba is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Cyprus', 'assets/images/flag-of-Cyprus.png', 100, 'Cyprus is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Czech Republic', 'assets/images/flag-of-Czech-Republic.png', 100, 'Czech Republic is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Denmark', 'assets/images/flag-of-Denmark.png', 100, 'Denmark is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Djibouti', 'assets/images/flag-of-Djibouti.png', 100, 'Djibouti is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Dominica', 'assets/images/flag-of-Dominica.png', 100, 'Dominica is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Dominican Republic', 'assets/images/flag-of-Dominican-Republic.png', 100, 'Dominican Republic is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Ecuador', 'assets/images/flag-of-Ecuador.png', 100, 'Ecuador is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Egypt', 'assets/images/flag-of-Egypt.png', 100, 'Egypt is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('El Salvador', 'assets/images/flag-of-El-Salvador.png', 100, 'El Salvador is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Equatorial Guinea', 'assets/images/flag-of-Equatorial-Guinea.png', 100, 'Equatorial Guinea is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Eritrea', 'assets/images/flag-of-Eritrea.png', 100, 'Eritrea is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Estonia', 'assets/images/flag-of-Estonia.png', 100, 'Estonia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Eswatini', 'assets/images/flag-of-Eswatini.png', 100, 'Eswatini is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Ethiopia', 'assets/images/flag-of-Ethiopia.png', 100, 'Ethiopia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Fiji', 'assets/images/flag-of-Fiji.png', 100, 'Fiji is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Finland', 'assets/images/flag-of-Finland.png', 100, 'Finland is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('France', 'assets/images/flag-of-France.png', 100, 'France is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Gabon', 'assets/images/flag-of-Gabon.png', 100, 'Gabon is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Gambia', 'assets/images/flag-of-Gambia.png', 100, 'Gambia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Georgia', 'assets/images/flag-of-Georgia.png', 100, 'Georgia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Germany', 'assets/images/flag-of-Germany.png', 100, 'Germany is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Ghana', 'assets/images/flag-of-Ghana.png', 100, 'Ghana is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Greece', 'assets/images/flag-of-Greece.png', 100, 'Greece is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Grenada', 'assets/images/flag-of-Grenada.png', 100, 'Grenada is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Guatemala', 'assets/images/flag-of-Guatemala.png', 100, 'Guatemala is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Guinea Bissau', 'assets/images/flag-of-Guinea-Bissau.png', 100, 'Guinea Bissau is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Guinea', 'assets/images/flag-of-Guinea.png', 100, 'Guinea is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Guyana', 'assets/images/flag-of-Guyana.png', 100, 'Guyana is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Haiti', 'assets/images/flag-of-Haiti.png', 100, 'Haiti is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Honduras', 'assets/images/flag-of-Honduras.png', 100, 'Honduras is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Hungary', 'assets/images/flag-of-Hungary.png', 100, 'Hungary is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Iceland', 'assets/images/flag-of-Iceland.png', 100, 'Iceland is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('India', 'assets/images/flag-of-India.png', 100, 'India is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Indonesia', 'assets/images/flag-of-Indonesia.png', 100, 'Indonesia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Iran', 'assets/images/flag-of-Iran.png', 100, 'Iran is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Iraq', 'assets/images/flag-of-Iraq.png', 100, 'Iraq is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Ireland', 'assets/images/flag-of-Ireland.png', 100, 'Ireland is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Israel', 'assets/images/flag-of-Israel.png', 100, 'Israel is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Italy', 'assets/images/flag-of-Italy.png', 100, 'Italy is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Jamaica', 'assets/images/flag-of-Jamaica.png', 100, 'Jamaica is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Japan', 'assets/images/flag-of-Japan.png', 100, 'Japan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Jordan', 'assets/images/flag-of-Jordan.png', 100, 'Jordan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Kazakhstan', 'assets/images/flag-of-Kazakhstan.png', 100, 'Kazakhstan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Kenya', 'assets/images/flag-of-Kenya.png', 100, 'Kenya is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Kiribati', 'assets/images/flag-of-Kiribati.png', 100, 'Kiribati is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Korea North', 'assets/images/flag-of-Korea-North.png', 100, 'Korea North is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Korea South', 'assets/images/flag-of-Korea-South.png', 100, 'Korea South is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Kosovo', 'assets/images/flag-of-Kosovo.png', 100, 'Kosovo is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Kuwait', 'assets/images/flag-of-Kuwait.png', 100, 'Kuwait is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Kyrgyzstan', 'assets/images/flag-of-Kyrgyzstan.png', 100, 'Kyrgyzstan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Laos', 'assets/images/flag-of-Laos.png', 100, 'Laos is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Latvia', 'assets/images/flag-of-Latvia.png', 100, 'Latvia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Lebanon', 'assets/images/flag-of-Lebanon.png', 100, 'Lebanon is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Lesotho', 'assets/images/flag-of-Lesotho.png', 100, 'Lesotho is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Liberia', 'assets/images/flag-of-Liberia.png', 100, 'Liberia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Libya', 'assets/images/flag-of-Libya.png', 100, 'Libya is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Liechtenstein', 'assets/images/flag-of-Liechtenstein.png', 100, 'Liechtenstein is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Lithuania', 'assets/images/flag-of-Lithuania.png', 100, 'Lithuania is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Luxembourg', 'assets/images/flag-of-Luxembourg.png', 100, 'Luxembourg is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Madagascar', 'assets/images/flag-of-Madagascar.png', 100, 'Madagascar is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Malawi', 'assets/images/flag-of-Malawi.png', 100, 'Malawi is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Malaysia', 'assets/images/flag-of-Malaysia.png', 100, 'Malaysia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Maldives', 'assets/images/flag-of-Maldives.png', 100, 'Maldives is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Mali', 'assets/images/flag-of-Mali.png', 100, 'Mali is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Malta', 'assets/images/flag-of-Malta.png', 100, 'Malta is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Marshall Islands', 'assets/images/flag-of-Marshall-Islands.png', 100, 'Marshall Islands is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Mauritania', 'assets/images/flag-of-Mauritania.png', 100, 'Mauritania is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Mauritius', 'assets/images/flag-of-Mauritius.png', 100, 'Mauritius is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Mexico', 'assets/images/flag-of-Mexico.png', 100, 'Mexico is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Micronesia', 'assets/images/flag-of-Micronesia.png', 100, 'Micronesia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Moldova', 'assets/images/flag-of-Moldova.png', 100, 'Moldova is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Monaco', 'assets/images/flag-of-Monaco.png', 100, 'Monaco is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Mongolia', 'assets/images/flag-of-Mongolia.png', 100, 'Mongolia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Montenegro', 'assets/images/flag-of-Montenegro.png', 100, 'Montenegro is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Morocco', 'assets/images/flag-of-Morocco.png', 100, 'Morocco is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Mozambique', 'assets/images/flag-of-Mozambique.png', 100, 'Mozambique is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Myanmar', 'assets/images/flag-of-Myanmar.png', 100, 'Myanmar is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Namibia', 'assets/images/flag-of-Namibia.png', 100, 'Namibia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Nauru', 'assets/images/flag-of-Nauru.png', 100, 'Nauru is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Nepal', 'assets/images/flag-of-Nepal.png', 100, 'Nepal is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Netherlands', 'assets/images/flag-of-Netherlands.png', 100, 'Netherlands is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('New Zealand', 'assets/images/flag-of-New-Zealand.png', 100, 'New Zealand is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Nicaragua', 'assets/images/flag-of-Nicaragua.png', 100, 'Nicaragua is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Niger', 'assets/images/flag-of-Niger.png', 100, 'Niger is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Nigeria', 'assets/images/flag-of-Nigeria.png', 100, 'Nigeria is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('North Macedonia', 'assets/images/flag-of-North-Macedonia.png', 100, 'North Macedonia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Norway', 'assets/images/flag-of-Norway.png', 100, 'Norway is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Oman', 'assets/images/flag-of-Oman.png', 100, 'Oman is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Pakistan', 'assets/images/flag-of-Pakistan.png', 100, 'Pakistan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Palau', 'assets/images/flag-of-Palau.png', 100, 'Palau is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Palestine', 'assets/images/flag-of-Palestine.png', 100, 'Palestine is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Panama', 'assets/images/flag-of-Panama.png', 100, 'Panama is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Papua New Guinea', 'assets/images/flag-of-Papua-New-Guinea.png', 100, 'Papua New Guinea is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Paraguay', 'assets/images/flag-of-Paraguay.png', 100, 'Paraguay is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Peru', 'assets/images/flag-of-Peru.png', 100, 'Peru is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Philippines', 'assets/images/flag-of-Philippines.png', 100, 'Philippines is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Poland', 'assets/images/flag-of-Poland.png', 100, 'Poland is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Portugal', 'assets/images/flag-of-Portugal.png', 100, 'Portugal is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Qatar', 'assets/images/flag-of-Qatar.png', 100, 'Qatar is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Romania', 'assets/images/flag-of-Romania.png', 100, 'Romania is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Russia', 'assets/images/flag-of-Russia.png', 100, 'Russia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Rwanda', 'assets/images/flag-of-Rwanda.png', 100, 'Rwanda is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Samoa', 'assets/images/flag-of-Samoa.png', 100, 'Samoa is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('San Marino', 'assets/images/flag-of-San-Marino.png', 100, 'San Marino is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Sao Tome and Principe', 'assets/images/flag-of-Sao-Tome-and-Principe.png', 100, 'Sao Tome and Principe is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Saudi Arabia', 'assets/images/flag-of-Saudi-Arabia.png', 100, 'Saudi Arabia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Senegal', 'assets/images/flag-of-Senegal.png', 100, 'Senegal is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Serbia', 'assets/images/flag-of-Serbia.png', 100, 'Serbia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Seychelles', 'assets/images/flag-of-Seychelles.png', 100, 'Seychelles is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Sierra Leone', 'assets/images/flag-of-Sierra-Leone.png', 100, 'Sierra Leone is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Singapore', 'assets/images/flag-of-Singapore.png', 100, 'Singapore is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Slovakia', 'assets/images/flag-of-Slovakia.png', 100, 'Slovakia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Slovenia', 'assets/images/flag-of-Slovenia.png', 100, 'Slovenia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Solomon Islands', 'assets/images/flag-of-Solomon-Islands.png', 100, 'Solomon Islands is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Somalia', 'assets/images/flag-of-Somalia.png', 100, 'Somalia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('South Africa', 'assets/images/flag-of-South-Africa.png', 100, 'South Africa is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('South Sudan', 'assets/images/flag-of-South-Sudan.png', 100, 'South Sudan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Spain', 'assets/images/flag-of-Spain.png', 100, 'Spain is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Sri Lanka', 'assets/images/flag-of-Sri-Lanka.png', 100, 'Sri Lanka is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('St Kitts Nevis', 'assets/images/flag-of-St-Kitts-Nevis.png', 100, 'St Kitts Nevis is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('St Lucia', 'assets/images/flag-of-St-Lucia.png', 100, 'St Lucia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('St Vincent the Grenadines', 'assets/images/flag-of-St-Vincent-the-Grenadines.png', 100, 'St Vincent the Grenadines is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Sudan', 'assets/images/flag-of-Sudan.png', 100, 'Sudan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Suriname', 'assets/images/flag-of-Suriname.png', 100, 'Suriname is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Sweden', 'assets/images/flag-of-Sweden.png', 100, 'Sweden is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Switzerland', 'assets/images/flag-of-Switzerland.png', 100, 'Switzerland is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Syria', 'assets/images/flag-of-Syria.png', 100, 'Syria is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Taiwan', 'assets/images/flag-of-Taiwan.png', 100, 'Taiwan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Tajikistan', 'assets/images/flag-of-Tajikistan.png', 100, 'Tajikistan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Tanzania', 'assets/images/flag-of-Tanzania.png', 100, 'Tanzania is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Thailand', 'assets/images/flag-of-Thailand.png', 100, 'Thailand is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Timor Leste', 'assets/images/flag-of-Timor-Leste.png', 100, 'Timor Leste is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Togo', 'assets/images/flag-of-Togo.png', 100, 'Togo is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Tonga', 'assets/images/flag-of-Tonga.png', 100, 'Tonga is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Trinidad and Tobago', 'assets/images/flag-of-Trinidad-and-Tobago.png', 100, 'Trinidad and Tobago is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Tunisia', 'assets/images/flag-of-Tunisia.png', 100, 'Tunisia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Turkey', 'assets/images/flag-of-Turkey.png', 100, 'Turkey is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Turkmenistan', 'assets/images/flag-of-Turkmenistan.png', 100, 'Turkmenistan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Tuvalu', 'assets/images/flag-of-Tuvalu.png', 100, 'Tuvalu is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Uganda', 'assets/images/flag-of-Uganda.png', 100, 'Uganda is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Ukraine', 'assets/images/flag-of-Ukraine.png', 100, 'Ukraine is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('United Arab Emirates', 'assets/images/flag-of-United-Arab-Emirates.png', 100, 'United Arab Emirates is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('United Kingdom', 'assets/images/flag-of-United-Kingdom.png', 100, 'United Kingdom is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('United States of America', 'assets/images/flag-of-United-States-of-America.png', 100, 'United States of America is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Uruguay', 'assets/images/flag-of-Uruguay.png', 100, 'Uruguay is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Uzbekistan', 'assets/images/flag-of-Uzbekistan.png', 100, 'Uzbekistan is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Vanuatu', 'assets/images/flag-of-Vanuatu.png', 100, 'Vanuatu is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Vatican City', 'assets/images/flag-of-Vatican-City.png', 100, 'Vatican City is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Venezuela', 'assets/images/flag-of-Venezuela.png', 100, 'Venezuela is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Vietnam', 'assets/images/flag-of-Vietnam.png', 100, 'Vietnam is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Yemen', 'assets/images/flag-of-Yemen.png', 100, 'Yemen is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Zambia', 'assets/images/flag-of-Zambia.png', 100, 'Zambia is a country of ...');
INSERT INTO country(name, flag, ratio, description) VALUES('Zimbabwe', 'assets/images/flag-of-Zimbabwe.png', 100, 'Zimbabwe is a country of ...');
SELECT * FROM country