/// Flutter icons Menu_Icon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Menu_Icon
///      fonts:
///       - asset: fonts/Menu_Icon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Menu_Icon {
  Menu_Icon._();

  static const _kFontFam = 'Menu_Icon';

  static const IconData info_outline = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData swords = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData open_book = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xf1a0, fontFamily: _kFontFam);
}
