enum Difficulty { EASY, NORMAL, HARD, UNLIMITED }
enum Continent {
  ASIA,
  EUROPE,
  AFRICA,
  AUSTRALIA,
  ANTARCTICA,
  NORTH_AMERICA,
  SOUTH_AMERICA
}
// enum RoundStatus { IDLE, PLAYING, OVER }
