enum Difficulty { EASY, NORMAL, HARD, ENDLESS }
enum Continent {
  ASIA,
  EUROPE,
  AFRICA,
  AUSTRALIAandOCEANIA,
  ASIAandEUROPE,
  NORTH_AMERICA,
  SOUTH_AMERICA,
  UNKNOWN,
}
// enum RoundStatus { IDLE, PLAYING, OVER }
